### ISSUE TITLE
zotero-picker incompatible with new zotero 5.0 development + (ongoing) zotero better-bibtex update

### ISSUE THREAD

**Issue by floriandierickx** [oztalha/zotero-picker#2]
Hello, this might not really be an 'issue' (depending on to which extent you're planning to keep this atom package), but at the moment the app seems not to be compatible with the new zotero 5.0 and better bibtex app. It's a pity it's not compatible anymore, I was a happy and very frequent user! Anyway, if you're planning to make it compatible again (or if it's not too much work), I would be very happy :)

**Comment by oztalha** [comment]
I'll try to look into that. I'm now in a transition state.
Btw, have you seen this: https://github.com/retorquere/zotero-better-bibtex

**Comment by gunwald** [comment]
I can confirm that the plugin does not work for Zotero 5.0. As I was a happy and frequent user too, an update would be greatly appreciated!

**Comment by happydemic** [comment]
@oztalha Did you know that the same person who does the BBT plugin also has an Atom package called [zotero-citations](https://atom.io/packages/zotero-citations), which uses the BBT picker to insert citations?

@gunwald, as I understand it, the underlying issue is that the Zotero picker comes from the [Better BibTeX](https://github.com/retorquere/zotero-better-bibtex) Zotero plugin, and the picker does not yet work in Zotero 5. Better BibTeX is under (very!) active development, but the citation picker (part of the CAYW feature) is [not yet working](https://github.com/retorquere/zotero-better-bibtex/issues/555#issuecomment-333490072).

**Comment by oztalha** [comment]
It now works.
